# Generated by Django 2.1.5 on 2019-01-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='icon_url',
            field=models.ImageField(default='default.jpg', upload_to='icons'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='deadline',
            field=models.DateField(),
        ),
    ]
